import { Routes, RouterModule, CanActivate } from '@angular/router';
import { Pages } from './pages.component';
import { ModuleWithProviders } from '@angular/core';
import { AuthGuard } from '../shared/auth-guard.service';
export const routes: Routes = [
{
    path: 'login',
    loadChildren: 'app/pages/login/login.module#LoginModule'
},
{
    path: 'register',
    loadChildren: 'app/pages/register/register.module#RegisterModule'
},
{
    path: 'forgot',
    loadChildren: 'app/pages/forgot/forgot.module#ForgotModule'
},
{
    path: 'change-password',
    loadChildren: 'app/pages/change-password/change-password.module#ChangePasswordModule', 
    canActivate: [AuthGuard]
},
{
    path: 'pages',
    component: Pages,
    children: [
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule' },
    { path: 'unauthorized', loadChildren: './unauthorized/unauthorized.module#UnauthorizedModule'},
    { path: 'bonificacions', loadChildren: './bonificacions/bonificacions.module#BonificacionsModule',
        canActivateChild: [AuthGuard] },
    { path: 'bonificacions/chofer/:idchofer', loadChildren: './bonificacions/bonificacions.module#BonificacionsModule'},
    { path: 'bonificacions/estado/:idestado', loadChildren: './bonificacions/bonificacions.module#BonificacionsModule'},
    { path: 'chofers', loadChildren: './chofers/chofers.module#ChofersModule',
        canActivateChild: [AuthGuard] },
    { path: 'chofers/estado/:idestado', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'chofers/estado/:idestado', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'chofers/persona/:idpersona', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'chofers/persona/:idpersona', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'chofers/persona/:idpersona', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'chofers/persona/:idpersona', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'chofers/persona/:idpersona', loadChildren: './chofers/chofers.module#ChofersModule'},
    { path: 'conceptos', loadChildren: './conceptos/conceptos.module#ConceptosModule',
        canActivateChild: [AuthGuard] },
    { path: 'corralons', loadChildren: './corralons/corralons.module#CorralonsModule',
        canActivateChild: [AuthGuard] },
    { path: 'corralons/estado/:idestado', loadChildren: './corralons/corralons.module#CorralonsModule'},
    { path: 'corralons/permisotaxiasignado/:idpermisotaxiasignado', loadChildren: './corralons/corralons.module#CorralonsModule'},
    { path: 'egresoconceptos', loadChildren: './egresoconceptos/egresoconceptos.module#EgresoconceptosModule',
        canActivateChild: [AuthGuard] },
    { path: 'egresoconceptos/concepto/:idconcepto', loadChildren: './egresoconceptos/egresoconceptos.module#EgresoconceptosModule'},
    { path: 'egresoconceptos/taller/:idtaller', loadChildren: './egresoconceptos/egresoconceptos.module#EgresoconceptosModule'},
    { path: 'enviotallers', loadChildren: './enviotallers/enviotallers.module#EnviotallersModule',
        canActivateChild: [AuthGuard] },
    { path: 'enviotallers/mantenimiento/:idmantenimiento', loadChildren: './enviotallers/enviotallers.module#EnviotallersModule'},
    { path: 'enviotallers/permisotaxiasignado/:idpermisotaxiasignado', loadChildren: './enviotallers/enviotallers.module#EnviotallersModule'},
    { path: 'enviotallers/taller/:idtaller', loadChildren: './enviotallers/enviotallers.module#EnviotallersModule'},
    { path: 'estados', loadChildren: './estados/estados.module#EstadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'liquidacions', loadChildren: './liquidacions/liquidacions.module#LiquidacionsModule',
        canActivateChild: [AuthGuard] },
    { path: 'liquidacions/chofer/:idchofer', loadChildren: './liquidacions/liquidacions.module#LiquidacionsModule'},
    { path: 'liquidacions/estado/:idestado', loadChildren: './liquidacions/liquidacions.module#LiquidacionsModule'},
    { path: 'liquidacions/permisotaxiasignado/:idpermisotaxiasignado', loadChildren: './liquidacions/liquidacions.module#LiquidacionsModule'},
    { path: 'mantenimientos', loadChildren: './mantenimientos/mantenimientos.module#MantenimientosModule',
        canActivateChild: [AuthGuard] },
    { path: 'mecanicos', loadChildren: './mecanicos/mecanicos.module#MecanicosModule',
        canActivateChild: [AuthGuard] },
    { path: 'mecanicos/persona/:idpersona', loadChildren: './mecanicos/mecanicos.module#MecanicosModule'},
    { path: 'mecanicos/taller/:idtaller', loadChildren: './mecanicos/mecanicos.module#MecanicosModule'},
    { path: 'ordens', loadChildren: './ordens/ordens.module#OrdensModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordens/estado/:idestado', loadChildren: './ordens/ordens.module#OrdensModule'},
    { path: 'ordens/vehiculoreparando/:idvehiculoreparando', loadChildren: './ordens/ordens.module#OrdensModule'},
    { path: 'orden_has_refaccions', loadChildren: './orden_has_refaccions/orden_has_refaccions.module#Orden_has_refaccionsModule',
        canActivateChild: [AuthGuard] },
    { path: 'orden_has_refaccions/orden/:idorden', loadChildren: './orden_has_refaccions/orden_has_refaccions.module#Orden_has_refaccionsModule'},
    { path: 'orden_has_refaccions/refaccion/:idrefaccion', loadChildren: './orden_has_refaccions/orden_has_refaccions.module#Orden_has_refaccionsModule'},
    { path: 'pagos', loadChildren: './pagos/pagos.module#PagosModule',
        canActivateChild: [AuthGuard] },
    { path: 'pagos/chofer/:idchofer', loadChildren: './pagos/pagos.module#PagosModule'},
    { path: 'pagos/estado/:idestado', loadChildren: './pagos/pagos.module#PagosModule'},
    { path: 'pagobonificacions', loadChildren: './pagobonificacions/pagobonificacions.module#PagobonificacionsModule',
        canActivateChild: [AuthGuard] },
    { path: 'pagobonificacions/bonificacion/:idbonificacion', loadChildren: './pagobonificacions/pagobonificacions.module#PagobonificacionsModule'},
    { path: 'pagobonificacions/pago/:idpago', loadChildren: './pagobonificacions/pagobonificacions.module#PagobonificacionsModule'},
    { path: 'pagofianzas', loadChildren: './pagofianzas/pagofianzas.module#PagofianzasModule',
        canActivateChild: [AuthGuard] },
    { path: 'pagofianzas/chofer/:idchofer', loadChildren: './pagofianzas/pagofianzas.module#PagofianzasModule'},
    { path: 'pagofianzas/pago/:idpago', loadChildren: './pagofianzas/pagofianzas.module#PagofianzasModule'},
    { path: 'pagoliquidacions', loadChildren: './pagoliquidacions/pagoliquidacions.module#PagoliquidacionsModule',
        canActivateChild: [AuthGuard] },
    { path: 'pagoliquidacions/chofer/:idchofer', loadChildren: './pagoliquidacions/pagoliquidacions.module#PagoliquidacionsModule'},
    { path: 'pagoliquidacions/pago/:idpago', loadChildren: './pagoliquidacions/pagoliquidacions.module#PagoliquidacionsModule'},
    { path: 'permisotaxis', loadChildren: './permisotaxis/permisotaxis.module#PermisotaxisModule',
        canActivateChild: [AuthGuard] },
    { path: 'permisotaxis/estado/:idestado', loadChildren: './permisotaxis/permisotaxis.module#PermisotaxisModule'},
    { path: 'permisotaxis/persona/:idpersona', loadChildren: './permisotaxis/permisotaxis.module#PermisotaxisModule'},
    { path: 'permisotaxis/vehiculo/:idvehiculo', loadChildren: './permisotaxis/permisotaxis.module#PermisotaxisModule'},



    { path: 'permisotaxiasignados', loadChildren: './permisotaxiasignados/permisotaxiasignados.module#PermisotaxiasignadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'permisotaxiasignados/chofer/:idchofer', loadChildren: './permisotaxiasignados/permisotaxiasignados.module#PermisotaxiasignadosModule'},
    { path: 'permisotaxiasignados/estado/:idestado', loadChildren: './permisotaxiasignados/permisotaxiasignados.module#PermisotaxiasignadosModule'},
    { path: 'permisotaxiasignados/permisotaxi/:idpermisotaxi', loadChildren: './permisotaxiasignados/permisotaxiasignados.module#PermisotaxiasignadosModule'},
    { path: 'personas', loadChildren: './personas/personas.module#PersonasModule',
        canActivateChild: [AuthGuard] },
        
    { path: 'reportes', loadChildren: './reportes/reportes.module#ReportesModule' },

    { path: 'refaccions', loadChildren: './refaccions/refaccions.module#RefaccionsModule',
        canActivateChild: [AuthGuard] },
    { path: 'refaccions/taller/:idtaller', loadChildren: './refaccions/refaccions.module#RefaccionsModule' },
    { path: 'si_modulos', loadChildren: './si_modulos/si_modulos.module#Si_modulosModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_permisos', loadChildren: './si_permisos/si_permisos.module#Si_permisosModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_permisos/si_modulo/:idsi_modulo', loadChildren: './si_permisos/si_permisos.module#Si_permisosModule'},
    { path: 'si_permisos/si_rol/:idsi_rol', loadChildren: './si_permisos/si_permisos.module#Si_permisosModule'},
    { path: 'si_reportes/si_modulo/:idsi_modulo', loadChildren: './si_reportes/si_reportes.module#Si_reportesModule'},
    { path: 'si_rols', loadChildren: './si_rols/si_rols.module#Si_rolsModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_users', loadChildren: './si_users/si_users.module#Si_usersModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_users/si_rol/:idsi_rol', loadChildren: './si_users/si_users.module#Si_usersModule'},
    { path: 'tallers', loadChildren: './tallers/tallers.module#TallersModule',
        canActivateChild: [AuthGuard] },
    { path: 'vehiculos', loadChildren: './vehiculos/vehiculos.module#VehiculosModule',
        canActivateChild: [AuthGuard] },
    { path: 'vehiculos/estado/:idestado', loadChildren: './vehiculos/vehiculos.module#VehiculosModule'},
    { path: 'vehiculos/persona/:idpersona', loadChildren: './vehiculos/vehiculos.module#VehiculosModule'},
    { path: 'vehiculoreparandos', loadChildren: './vehiculoreparandos/vehiculoreparandos.module#VehiculoreparandosModule',
        canActivateChild: [AuthGuard] },
    { path: 'vehiculoreparandos/enviotaller/:idenviotaller', loadChildren: './vehiculoreparandos/vehiculoreparandos.module#VehiculoreparandosModule'},
    { path: 'vehiculoreparandos/estado/:idestado', loadChildren: './vehiculoreparandos/vehiculoreparandos.module#VehiculoreparandosModule'},
    { path: 'vehiculoreparandos/mecanico/:idmecanico', loadChildren: './vehiculoreparandos/vehiculoreparandos.module#VehiculoreparandosModule'},
    { path: 'vehiculoreparandos/permisotaxiasignado/:idpermisotaxiasignado', loadChildren: './vehiculoreparandos/vehiculoreparandos.module#VehiculoreparandosModule'},
    { path: 'vehiculoreparandos/taller/:idtaller', loadChildren: './vehiculoreparandos/vehiculoreparandos.module#VehiculoreparandosModule'},
    ]
}
];
export const routing: ModuleWithProviders = RouterModule.forChild(routes);
